# Generated by Django 5.1 on 2024-08-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_botstatistics_user_appointment_alter_event_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
