# Generated by Django 5.1 on 2024-08-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
