# Generated by Django 5.1 on 2024-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(1, 'confirmed'), (2, 'awaiting'), (3, 'declined')], max_length=40),
        ),
    ]
