# Generated by Django 5.1 on 2024-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_alter_appointment_duration_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
