# Generated by Django 5.1 on 2024-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0008_remove_appointment_duration_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
