# Generated by Django 5.1 on 2024-09-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_event_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.event')),
            ],
        ),
    ]
