# Generated by Django 5.1 on 2024-09-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_publicevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicevents',
            name='is_public',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=40),
        ),
    ]
