# Generated by Django 5.1 on 2024-09-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0011_alter_publicevents_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicevents',
            old_name='is_public',
            new_name='status',
        ),
    ]
